name: "Check PHP Code Styling"

on:
  push:
    paths:
      - "**.php"
      - "pint.json"
  pull_request:
    paths:
      - "**.php"
      - "pint.json"

permissions:
  contents: read

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup PHP
        uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45 # v2
        with:
          php-version: "8.4"
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # v3

      - name: Check PHP code style
        run: vendor/bin/pint --test
